on:
  public:
  push:
    branches:
      - feature/make-private

jobs:
  set-repo-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 2 hours
        run: sleep 7200
      - name: Set repo to internal
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.BRANCH_BYPASS_TOKEN}}
          script: |
            github.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              visibility: 'internal'
            })
